version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 1
    target-branch: "main"
