name: GenerateConfig

on: workflow_dispatch

jobs:
  GenerateConfig:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env: 
      IAM_INSTANCE_PROFILE_ARN: ${{secrets.IAM_INSTANCE_PROFILE_ARN}} 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install xmllint
      run: sudo apt-get update && sudo apt-get install libxml2-utils
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        role-to-assume: ${{secrets.AMI_GENERATE_CONFIG_ROLE}}
        aws-region: us-west-2
    - name: Configure prereqs
      run: |
        git config --global user.name "GenerateConfig Action"
        git config --global user.email "gcaction@github.com"
    - name: Check AL1 Updates
      run: ./scripts/check-update.sh al1
    - name: Check AL2 Base AMI Update
      run: ./scripts/check-update.sh al2
    - name: Check AL2023 Base AMI Update
      run: ./scripts/check-update.sh al2023
    - name: Commit and Push Changes if Update Is Required
      run: |
        git commit -m "Release Kickoff"
        git status
        git push